name: DineIn start

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master   
      - name: Build app
        run: make build-production
      - name: Start app
        run: make start-production
