name: DineIn start

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master   
      - name: Build images
        run: |
          ls
          make build-production
          make start-production
